/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountsPayable {
  'title' : string,
  'description' : string,
  'keyExpertise' : Array<string>,
}
export interface AccountsReceivable {
  'title' : string,
  'description' : string,
  'keyExpertise' : Array<string>,
}
export interface ContactConfirmation { 'message' : string, 'success' : boolean }
export interface ContactFormInput {
  'name' : string,
  'email' : string,
  'company' : [] | [string],
  'message' : string,
}
export interface ContactInquiry {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'company' : [] | [string],
  'message' : string,
  'timestamp' : bigint,
}
export interface Experience {
  'duration' : string,
  'description' : string,
  'keyExpertise' : [] | [Array<string>],
  'company' : string,
  'position' : string,
  'focusAreas' : Array<FocusArea>,
}
export type ExternalBlob = Uint8Array;
export interface FocusArea { 'title' : string, 'description' : string }
export interface LogoReference {
  'id' : bigint,
  'blob' : ExternalBlob,
  'name' : string,
}
export interface PortfolioData {
  'tools' : Array<Tool>,
  'about' : string,
  'accountsReceivable' : [] | [AccountsReceivable],
  'experience' : Array<Experience>,
  'accountsPayable' : AccountsPayable,
  'services' : Array<Service>,
}
export interface Service {
  'title' : string,
  'description' : string,
  'price' : [] | [string],
}
export interface Tool {
  'icon' : string,
  'name' : string,
  'notes' : string,
  'expertiseLevel' : string,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContactInquiry' : ActorMethod<[bigint], undefined>,
  'deleteLogoReference' : ActorMethod<[bigint], boolean>,
  'getAllExperience' : ActorMethod<[], Array<Experience>>,
  'getAllLogoReferences' : ActorMethod<[], Array<LogoReference>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'getContactInquiry' : ActorMethod<[bigint], [] | [ContactInquiry]>,
  'getExperienceByCompany' : ActorMethod<[string], Array<Experience>>,
  'getLogoReference' : ActorMethod<[bigint], [] | [LogoReference]>,
  'getLogoReferenceInternal' : ActorMethod<[bigint], ExternalBlob>,
  'getPortfolioData' : ActorMethod<[], PortfolioData>,
  'getServiceInfo' : ActorMethod<[], Array<Service>>,
  'getToolInfo' : ActorMethod<[], Array<Tool>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializePortfolio' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeService' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[ContactFormInput], ContactConfirmation>,
  'updateAbout' : ActorMethod<[string], undefined>,
  'updateAccountsPayable' : ActorMethod<[AccountsPayable], undefined>,
  'updateAccountsReceivable' : ActorMethod<[AccountsReceivable], undefined>,
  'updateExperience' : ActorMethod<[bigint, Experience], undefined>,
  'updateService' : ActorMethod<[bigint, Service], undefined>,
  'updateTool' : ActorMethod<[bigint, Tool], undefined>,
  'uploadLogo' : ActorMethod<[ExternalBlob, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];