/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FocusArea = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const Experience = IDL.Record({
  'duration' : IDL.Text,
  'description' : IDL.Text,
  'keyExpertise' : IDL.Opt(IDL.Vec(IDL.Text)),
  'company' : IDL.Text,
  'position' : IDL.Text,
  'focusAreas' : IDL.Vec(FocusArea),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LogoReference = IDL.Record({
  'id' : IDL.Nat,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : IDL.Nat,
});
export const Tool = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'expertiseLevel' : IDL.Text,
});
export const AccountsReceivable = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'keyExpertise' : IDL.Vec(IDL.Text),
});
export const AccountsPayable = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'keyExpertise' : IDL.Vec(IDL.Text),
});
export const PortfolioData = IDL.Record({
  'tools' : IDL.Vec(Tool),
  'about' : IDL.Text,
  'accountsReceivable' : IDL.Opt(AccountsReceivable),
  'experience' : IDL.Vec(Experience),
  'accountsPayable' : AccountsPayable,
  'services' : IDL.Vec(Service),
});
export const ContactFormInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
});
export const ContactConfirmation = IDL.Record({
  'message' : IDL.Text,
  'success' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addService' : IDL.Func([Service], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContactInquiry' : IDL.Func([IDL.Nat], [], []),
  'deleteLogoReference' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllExperience' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getAllLogoReferences' : IDL.Func([], [IDL.Vec(LogoReference)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getContactInquiry' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ContactInquiry)],
      ['query'],
    ),
  'getExperienceByCompany' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Experience)],
      ['query'],
    ),
  'getLogoReference' : IDL.Func([IDL.Nat], [IDL.Opt(LogoReference)], ['query']),
  'getLogoReferenceInternal' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
  'getPortfolioData' : IDL.Func([], [PortfolioData], ['query']),
  'getServiceInfo' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getToolInfo' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializePortfolio' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeService' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([ContactFormInput], [ContactConfirmation], []),
  'updateAbout' : IDL.Func([IDL.Text], [], []),
  'updateAccountsPayable' : IDL.Func([AccountsPayable], [], []),
  'updateAccountsReceivable' : IDL.Func([AccountsReceivable], [], []),
  'updateExperience' : IDL.Func([IDL.Nat, Experience], [], []),
  'updateService' : IDL.Func([IDL.Nat, Service], [], []),
  'updateTool' : IDL.Func([IDL.Nat, Tool], [], []),
  'uploadLogo' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FocusArea = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const Experience = IDL.Record({
    'duration' : IDL.Text,
    'description' : IDL.Text,
    'keyExpertise' : IDL.Opt(IDL.Vec(IDL.Text)),
    'company' : IDL.Text,
    'position' : IDL.Text,
    'focusAreas' : IDL.Vec(FocusArea),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LogoReference = IDL.Record({
    'id' : IDL.Nat,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : IDL.Nat,
  });
  const Tool = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'expertiseLevel' : IDL.Text,
  });
  const AccountsReceivable = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'keyExpertise' : IDL.Vec(IDL.Text),
  });
  const AccountsPayable = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'keyExpertise' : IDL.Vec(IDL.Text),
  });
  const PortfolioData = IDL.Record({
    'tools' : IDL.Vec(Tool),
    'about' : IDL.Text,
    'accountsReceivable' : IDL.Opt(AccountsReceivable),
    'experience' : IDL.Vec(Experience),
    'accountsPayable' : AccountsPayable,
    'services' : IDL.Vec(Service),
  });
  const ContactFormInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
  });
  const ContactConfirmation = IDL.Record({
    'message' : IDL.Text,
    'success' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addService' : IDL.Func([Service], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContactInquiry' : IDL.Func([IDL.Nat], [], []),
    'deleteLogoReference' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllExperience' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getAllLogoReferences' : IDL.Func([], [IDL.Vec(LogoReference)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getContactInquiry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ContactInquiry)],
        ['query'],
      ),
    'getExperienceByCompany' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Experience)],
        ['query'],
      ),
    'getLogoReference' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(LogoReference)],
        ['query'],
      ),
    'getLogoReferenceInternal' : IDL.Func([IDL.Nat], [ExternalBlob], ['query']),
    'getPortfolioData' : IDL.Func([], [PortfolioData], ['query']),
    'getServiceInfo' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getToolInfo' : IDL.Func([], [IDL.Vec(Tool)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializePortfolio' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeService' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [ContactFormInput],
        [ContactConfirmation],
        [],
      ),
    'updateAbout' : IDL.Func([IDL.Text], [], []),
    'updateAccountsPayable' : IDL.Func([AccountsPayable], [], []),
    'updateAccountsReceivable' : IDL.Func([AccountsReceivable], [], []),
    'updateExperience' : IDL.Func([IDL.Nat, Experience], [], []),
    'updateService' : IDL.Func([IDL.Nat, Service], [], []),
    'updateTool' : IDL.Func([IDL.Nat, Tool], [], []),
    'uploadLogo' : IDL.Func([ExternalBlob, IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };