/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PortfolioData {
    tools: Array<Tool>;
    about: string;
    accountsReceivable?: AccountsReceivable;
    experience: Array<Experience>;
    accountsPayable: AccountsPayable;
    services: Array<Service>;
}
export interface LogoReference {
    id: bigint;
    blob: ExternalBlob;
    name: string;
}
export interface FocusArea {
    title: string;
    description: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    title: string;
    description: string;
    price?: string;
}
export interface AccountsPayable {
    title: string;
    description: string;
    keyExpertise: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface ContactConfirmation {
    message: string;
    success: boolean;
}
export interface AccountsReceivable {
    title: string;
    description: string;
    keyExpertise: Array<string>;
}
export interface Experience {
    duration: string;
    description: string;
    keyExpertise?: Array<string>;
    company: string;
    position: string;
    focusAreas: Array<FocusArea>;
}
export interface Tool {
    icon: string;
    name: string;
    notes: string;
    expertiseLevel: string;
}
export interface ContactInquiry {
    id: bigint;
    name: string;
    email: string;
    company?: string;
    message: string;
    timestamp: bigint;
}
export interface ContactFormInput {
    name: string;
    email: string;
    company?: string;
    message: string;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addService(service: Service): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteContactInquiry(id: bigint): Promise<void>;
    deleteLogoReference(id: bigint): Promise<boolean>;
    getAllExperience(): Promise<Array<Experience>>;
    getAllLogoReferences(): Promise<Array<LogoReference>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactInquiries(): Promise<Array<ContactInquiry>>;
    getContactInquiry(id: bigint): Promise<ContactInquiry | null>;
    getExperienceByCompany(company: string): Promise<Array<Experience>>;
    getLogoReference(id: bigint): Promise<LogoReference | null>;
    getLogoReferenceInternal(id: bigint): Promise<ExternalBlob>;
    getPortfolioData(): Promise<PortfolioData>;
    getServiceInfo(): Promise<Array<Service>>;
    getToolInfo(): Promise<Array<Tool>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializePortfolio(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    removeService(index: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContactForm(input: ContactFormInput): Promise<ContactConfirmation>;
    updateAbout(content: string): Promise<void>;
    updateAccountsPayable(accountsPayable: AccountsPayable): Promise<void>;
    updateAccountsReceivable(accountsReceivable: AccountsReceivable): Promise<void>;
    updateExperience(index: bigint, experience: Experience): Promise<void>;
    updateService(index: bigint, service: Service): Promise<void>;
    updateTool(index: bigint, tool: Tool): Promise<void>;
    uploadLogo(blob: ExternalBlob, name: string): Promise<bigint>;
}
import type { AccountsPayable as _AccountsPayable, AccountsReceivable as _AccountsReceivable, ContactFormInput as _ContactFormInput, ContactInquiry as _ContactInquiry, Experience as _Experience, ExternalBlob as _ExternalBlob, FocusArea as _FocusArea, LogoReference as _LogoReference, PortfolioData as _PortfolioData, Service as _Service, Tool as _Tool, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addService(arg0: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(to_candid_Service_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(to_candid_Service_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteContactInquiry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContactInquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContactInquiry(arg0);
            return result;
        }
    }
    async deleteLogoReference(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLogoReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLogoReference(arg0);
            return result;
        }
    }
    async getAllExperience(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExperience();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExperience();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLogoReferences(): Promise<Array<LogoReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLogoReferences();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLogoReferences();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInquiries(): Promise<Array<ContactInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInquiries();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInquiries();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactInquiry(arg0: bigint): Promise<ContactInquiry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInquiry(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInquiry(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExperienceByCompany(arg0: string): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExperienceByCompany(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExperienceByCompany(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogoReference(arg0: bigint): Promise<LogoReference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogoReference(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogoReference(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogoReferenceInternal(arg0: bigint): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogoReferenceInternal(arg0);
                return from_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogoReferenceInternal(arg0);
            return from_candid_ExternalBlob_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioData(): Promise<PortfolioData> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioData();
                return from_candid_PortfolioData_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioData();
            return from_candid_PortfolioData_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceInfo(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceInfo();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceInfo();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToolInfo(): Promise<Array<Tool>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolInfo();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializePortfolio(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializePortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializePortfolio();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeService(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeService(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitContactForm(arg0: ContactFormInput): Promise<ContactConfirmation> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(to_candid_ContactFormInput_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(to_candid_ContactFormInput_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAbout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAbout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAbout(arg0);
            return result;
        }
    }
    async updateAccountsPayable(arg0: AccountsPayable): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccountsPayable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccountsPayable(arg0);
            return result;
        }
    }
    async updateAccountsReceivable(arg0: AccountsReceivable): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAccountsReceivable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAccountsReceivable(arg0);
            return result;
        }
    }
    async updateExperience(arg0: bigint, arg1: Experience): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExperience(arg0, to_candid_Experience_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExperience(arg0, to_candid_Experience_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateService(arg0: bigint, arg1: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateService(arg0, to_candid_Service_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateService(arg0, to_candid_Service_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTool(arg0: bigint, arg1: Tool): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTool(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTool(arg0, arg1);
            return result;
        }
    }
    async uploadLogo(arg0: ExternalBlob, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadLogo(await to_candid_ExternalBlob_n43(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadLogo(await to_candid_ExternalBlob_n43(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
}
function from_candid_ContactInquiry_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactInquiry): ContactInquiry {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Experience_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Experience): Experience {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_LogoReference_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LogoReference): Promise<LogoReference> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PortfolioData_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioData): PortfolioData {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ContactInquiry]): ContactInquiry | null {
    return value.length === 0 ? null : from_candid_ContactInquiry_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LogoReference]): Promise<LogoReference | null> {
    return value.length === 0 ? null : await from_candid_LogoReference_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccountsReceivable]): AccountsReceivable | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: string;
    description: string;
    keyExpertise: [] | [Array<string>];
    company: string;
    position: string;
    focusAreas: Array<_FocusArea>;
}): {
    duration: string;
    description: string;
    keyExpertise?: Array<string>;
    company: string;
    position: string;
    focusAreas: Array<FocusArea>;
} {
    return {
        duration: value.duration,
        description: value.description,
        keyExpertise: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.keyExpertise)),
        company: value.company,
        position: value.position,
        focusAreas: value.focusAreas
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: _ExternalBlob;
    name: string;
}): Promise<{
    id: bigint;
    blob: ExternalBlob;
    name: string;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.blob),
        name: value.name
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    email: string;
    company: [] | [string];
    message: string;
    timestamp: bigint;
}): {
    id: bigint;
    name: string;
    email: string;
    company?: string;
    message: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        email: value.email,
        company: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.company)),
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tools: Array<_Tool>;
    about: string;
    accountsReceivable: [] | [_AccountsReceivable];
    experience: Array<_Experience>;
    accountsPayable: _AccountsPayable;
    services: Array<_Service>;
}): {
    tools: Array<Tool>;
    about: string;
    accountsReceivable?: AccountsReceivable;
    experience: Array<Experience>;
    accountsPayable: AccountsPayable;
    services: Array<Service>;
} {
    return {
        tools: value.tools,
        about: value.about,
        accountsReceivable: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.accountsReceivable)),
        experience: from_candid_vec_n12(_uploadFile, _downloadFile, value.experience),
        accountsPayable: value.accountsPayable,
        services: from_candid_vec_n34(_uploadFile, _downloadFile, value.services)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    price: [] | [string];
}): {
    title: string;
    description: string;
    price?: string;
} {
    return {
        title: value.title,
        description: value.description,
        price: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.price))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Experience>): Array<Experience> {
    return value.map((x)=>from_candid_Experience_n13(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LogoReference>): Promise<Array<LogoReference>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LogoReference_n17(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ContactInquiry>): Array<ContactInquiry> {
    return value.map((x)=>from_candid_ContactInquiry_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n35(_uploadFile, _downloadFile, x));
}
function to_candid_ContactFormInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContactFormInput): _ContactFormInput {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_Experience_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Experience): _Experience {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Service_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: string;
    company?: string;
    message: string;
}): {
    name: string;
    email: string;
    company: [] | [string];
    message: string;
} {
    return {
        name: value.name,
        email: value.email,
        company: value.company ? candid_some(value.company) : candid_none(),
        message: value.message
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: string;
    description: string;
    keyExpertise?: Array<string>;
    company: string;
    position: string;
    focusAreas: Array<FocusArea>;
}): {
    duration: string;
    description: string;
    keyExpertise: [] | [Array<string>];
    company: string;
    position: string;
    focusAreas: Array<_FocusArea>;
} {
    return {
        duration: value.duration,
        description: value.description,
        keyExpertise: value.keyExpertise ? candid_some(value.keyExpertise) : candid_none(),
        company: value.company,
        position: value.position,
        focusAreas: value.focusAreas
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    price?: string;
}): {
    title: string;
    description: string;
    price: [] | [string];
} {
    return {
        title: value.title,
        description: value.description,
        price: value.price ? candid_some(value.price) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
